version: '2'
services:
# Front End
  frontend:
    container_name: FrontEnd
    build: ./frontend
    ports:
      - "4200:4200"
# Service #0 API Gateway
  apigateway:
    container_name: APIGateway
    build: ./backend/APIGateway
    ports:
      - "8080:8080"
# Service #1 Books Service
  books:
    container_name: BooksService
    build: ./backend/booksservice
    ports:
      - "8084:8084"
# Service #2 Customers Service
  customers:
    container_name: CustomersService
    build: ./backend/customersservice
    ports:
      - "8082:8082"
# Service #3 Orders Service
  orders:
    container_name: OrdersService
    build: ./backend/ordersservice
    ports:
      - "8083:8083"
# MongoDB
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    volumes:
      - ../data/db:/data/db
# MongoDB GUI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"