version: '3'
services:
# Service #0 API Gateway
  apigateway:
    build: ./APIGateway
    ports:
      - "8080:8080"
# Service #1 Books Service
  books:
    build: ./booksservice
    ports:
      - "8084:8084"
# Service #2 Customers Service
  customers:
    build: ./customersservice
    ports:
      - "8082:8082"
# Service #3 Orders Service
  orders:
    build: ./ordersservice
    ports:
      - "8083:8083"
# MongoDB
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    volumes:
      - ../data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

